7439ª sesión , celebrada el 11 de mayo de 2015 .
el propio eiil ha publicado vídeos en los que se muestran imágenes de personas sometidas a una serie de castigos atroces , entre otras cosas , personas lapidadas , obligadas a saltar de edificios , decapitadas y crucificadas .
el unicef pagó ayudas monetarias de urgencia para asistir a decenas de miles de familias desplazadas en los campamentos y el acnur distribuyó asistencia en metálico a familias de desplazados internos en situación vulnerable .
31 . reconoce que el mecanismo africano de evaluación entre pares ha contribuido de forma importante , desde su inicio , a mejorar la gobernanza y apoyar el desarrollo socioeconómico de los países africanos , y recuerda en ese sentido el debate del panel de alto nivel que tuvo lugar el 21 de octubre de 2013 sobre la innovación de áfrica en materia de gobernanza a lo largo de los 10 años del mecanismo africano de evaluación entre pares , organizado durante el sexagésimo octavo período de sesiones de la asamblea general para conmemorar el décimo aniversario del mecanismo ;
los diferenciales entre los bonos soberanos en alemania y otros países se mantuvieron relativamente al margen de las incertidumbres políticas y de los mercados relacionadas con grecia a finales de 2014 y principios de 2015 .
la supresión de la tasa de cambio mínima frente al euro llevó aparejado un nuevo movimiento negativo de las tasas de interés para los depósitos a la vista , que alcanzaron el 0,75 % , a fin de reducir las presiones a favor de la apreciación y el consiguiente endurecimiento de las condiciones monetarias .
que se celebrará el jueves 2 de abril de 2015 a las 10.15 horas
siguiendo instrucciones de mi gobierno , tengo el honor de transmitirle adjunta una lista de los nombres de 96 ciudadanos sirios , de los cuales 41 son niños , que murieron en alepo a manos de los grupos terroristas durante el período comprendido entre el 13 de abril y el 7 de mayo de 2015 ( véase el anexo ) .
12 . reitera que las personas y entidades respecto de las cuales el comité determine que han infringido las disposiciones de la resolución 1970 ( 2011 ) , incluido el embargo de armas , o ayudado a otros a hacerlo , podrán ser designadas , y hace notar que esto incluye a quienes ayuden a infringir la congelación de activos y la prohibición de viajar impuestas por la resolución 1970 ( 2011 ) ;
23 . apoya los esfuerzos de las autoridades libias por recuperar los fondos malversados bajo el régimen de qadhafi y , a este respecto , alienta a las autoridades libias y a los estados miembros que hayan congelado activos atendiendo a las resoluciones 1970 ( 2011 ) y 1973 ( 2011 ) , modificadas mediante la resolución 2009 ( 2011 ) , a que se consulten mutuamente respecto de las reclamaciones de fondos malversados y cuestiones de propiedad conexas ;
comité del consejo de seguridad establecido en virtud de la resolución 1518 ( 2003 )
la retirada de bélgica , que será efectiva el 31 de diciembre de 2015 , así como la adhesión de las islas marshall , que se produjo el 16 de marzo de 2015 , se han tenido en cuenta a efectos del cálculo del coeficiente , y , por tanto , en el cálculo se han incluido 169 países .
1 . aprobación del orden del día .
13 . recalcamos la necesidad de acelerar los esfuerzos a todos los niveles para alcanzar los objetivos del acuerdo internacional sobre los bosques después de 2015 y la necesidad de establecer un acuerdo más firme , eficaz y sólido para el período comprendido entre 2015 y 2030 ;
transporte aéreo
la conferencia reafirma que la estricta observancia de todas las disposiciones del tratado sigue siendo fundamental para lograr los objetivos comunes de lograr la eliminación total de las armas nucleares , evitar que , en cualesquiera circunstancias , continúe el uso y la proliferación de las armas nucleares y de preservar la contribución esencial del tratado a la paz y la seguridad .
la conferencia afirma que , en espera del logro de este objetivo , redunda en interés de la propia supervivencia de la humanidad que las armas nucleares nunca se vuelvan a utilizar .
las distintas actividades de capacitación se enumeran en el cuadro 2 .
este prohíbe obtener visado a las personas que sean o pasen a ser objeto de una resolución del consejo que prohíba a australia autorizar su entrada o tránsito por territorio australiano , y , si el visado ya ha sido otorgado , prevé su cancelación , en cumplimiento de las obligaciones dimanantes de la resolución pertinente del consejo .
recalcando la importancia de la declaración política sobre el vih y el sida : intensificación de nuestro esfuerzo para eliminar el vih y el sida , aprobada en la reunión de alto nivel de la asamblea general sobre el vih y el sida el 10 de junio de 2011
en la 7453ª sesión del consejo de seguridad , celebrada el 29 de mayo de 2015 , en relación con el examen del tema titulado &quot; amenazas a la paz y la seguridad internacionales causadas por actos terroristas , &quot; la presidencia hizo la siguiente declaración en nombre del consejo :
tras su validación por la junta , el programa se puso en marcha el 20 de abril durante el 25o período de sesiones del consejo de administración del programa de las naciones unidas para los asentamientos humanos , bajo el liderazgo de finlandia y con la participación del pnuma , el world green building council y el royal melbourne institute of technology en calidad de codirectores .
5.1 eficacia y eficiencia de la asistencia técnica de tecnología de la información prestada al centro regional de servicios y las misiones clientes
a representa la dotación máxima autorizada por el consejo de seguridad en su resolución 2124 ( 2013 ) , con efecto a partir del 1 de enero de 2014 .
servicios de gestión estratégica
alentando a que continúen los esfuerzos del secretario general de las naciones unidas , la conferencia internacional sobre la región de los grandes lagos ( cirgl ) , la comunidad de áfrica meridional para el desarrollo ( sadc ) y la unión africana por restaurar la paz y la seguridad en el este de la república democrática del congo , alentando al gobierno de la república democrática del congo a que asegure una estrecha y continua cooperación con ellos y otros asociados internacionales , y reconociendo los esfuerzos del gobierno de la república democrática del congo encaminados al logro de la paz y el desarrollo nacional ,
instamos a los cinco estados poseedores de armas nucleares , que son partes en el tratado sobre la no proliferación de las armas nucleares , a que ratifiquen el protocolo lo antes posible , lo que permitirá concluir el proceso de institucionalización oficial de la zona y elevar considerablemente el nivel de confianza mutua y de seguridad .
un elemento fundamental es el despliegue de una fuerza de reacción rápida de un batallón , con vocación para intervenir en liberia , según sea necesario .
de conformidad con el artículo 15 del reglamento provisional del consejo de seguridad , el secretario general comunica que ha recibido del representante permanente de la federación de rusia ante las naciones unidas cartas de fecha 16 de marzo de 2015 en que se indica que la sra. olga vladimirovna mozolina y el sr. egor sergeevich shulgin han sido nombrados representantes suplentes de la federación de rusia en el consejo de seguridad .
en la misma sesión , la comisión designó al vicepresidente , rubén armando escalante hasbún ( el salvador ) , para que presidiera las consultas oficiosas .
que se celebrará el martes 12 de mayo de 2015 , a las 15.00 horas
período de sesiones de 2015
al mismo tiempo , una evaluación preliminar de la financiación acelerada ( recursos nuevos y adicionales prometidos en 2009 por los países desarrollados para la mitigación del cambio climático y la adaptación a sus efectos durante el 15 ° período de sesiones de la conferencia de las partes en la convención marco de las naciones unidas sobre el cambio climático ) reveló que el 80 % de esas corrientes también se contabilizaban como asistencia oficial para el desarrollo y se desembolsaban por medio de modalidades similares , en gran medida a través de canales bilaterales .
en ese contexto , el foro sobre cooperación para el desarrollo podría servir de plataforma adecuada para la rendición mutua de cuentas a nivel mundial , mientras que la reunión especial de alto nivel podría seguir siendo un foro en el que los gobiernos , los principales interesados institucionales , la sociedad civil y el sector empresarial coordinen sus actividades de aplicación en el contexto de la agenda para el desarrollo después de 2015 .
3 . pone de relieve la importancia de promover una cultura de rendición de cuentas , gestión basada en los resultados , gestión de riesgos institucionales y control interno a todos los niveles de la secretaría mediante el liderazgo y el compromiso continuos de los funcionarios directivos superiores , y reitera su solicitud de que el secretario general adopte medidas apropiadas a tal efecto , incluida la capacitación del personal competente ;
en mi calidad de representante del actual presidente de la unión africana , tengo el honor de transmitir por la presente un comunicado de prensa aprobado el 30 de abril de 2015 por el consejo de paz y seguridad de la unión africana en su 503a sesión para dar seguimiento al comunicado que había aprobado durante su 496ª sesión , celebrada el 27 de marzo de 2015 , sobre la situación en el sáhara occidental ( véase el anexo ) .
comunicado de prensa
asimismo , se informó a la comisión de que , durante la fase de liquidación de una misión , se reducían los plazos para la aplicación de las medidas de anulación en libros y enajenación de activos con el fin de poder cumplir la fecha fijada en el mandato para la finalización del período de liquidación .
misión integrada de las naciones unidas en timor-leste
también es importante elaborar indicadores adecuados de integración de políticas , teniendo en cuenta la labor de la organización de cooperación y desarrollo económicos en esta esfera .
la capacidad de formulación de políticas podría fortalecerse mediante la utilización de enfoques basados en la solución de problemas con el apoyo de juegos de instrumentos y con referencia a las buenas prácticas que puedan adaptarse a un contexto particular .
de conformidad con lo dispuesto en el párrafo 36 de los términos de referencia , los resúmenes de los informes sobre los países realizados antes del sexto período de sesiones se traducirán a los seis idiomas oficiales de las naciones unidas y se publicarán como documentos del grupo de examen de la aplicación solo con fines informativos .
1 . por carta de fecha 10 de abril de 2015 , la oficina permanente de la conferencia de la haya de derecho internacional privado ( la &quot; conferencia de la haya &quot; ) solicitó a la comisión que considerara la posibilidad de hacer suyos los principios sobre la elección de la ley aplicable a los contratos comerciales internacionales ( los &quot; principios de la haya &quot; ) .
europa central y oriental y la comunidad de estados independientes
informes periódicos del secretario general sobre el mejoramiento de la situación financiera de las naciones unidas
que se celebrará a puerta cerrada el martes 8 de abril de 2015 , a las 10.00 horas
el ministerio de relaciones exteriores y cooperación internacional informa a la opinión pública nacional e internacional que el gobierno de burundi felicita a las fuerzas de defensa y seguridad por haber frustrado un intento de golpe de estado que tuvo lugar los días 13 y 14 de mayo de 2015 .
el ministerio de relaciones exteriores y cooperación internacional desea reiterar el agradecimiento del gobierno de burundi a los países amigos y los asociados que apoyan el respeto a la legalidad y las instituciones existentes en burundi .
el gobierno de malasia también ha introducido una disposición especial en el proyecto de ley ( enmienda ) de la comisión de valores de 2015 para otorgar a la comisión de valores de malasia autoridad para dar instrucciones a sus intermediarios autorizados a fin de que congelen los activos o las cuentas de las personas y entidades designadas por el comité .
que se celebrará el martes 28 de abril de 2015 , a las 10.46 horas
adición
en todas esas resoluciones se apoyan las actividades para complementar la rendición de cuentas y la supervisión mediante las evaluaciones y las lecciones aprendidas , aplicando incluso la experiencia adquirida en los procesos de programación .
cuestiones relativas a los programas : evaluación
a partir de la crisis financiera de 2009 , la demanda interna ha sido el principal motor de crecimiento de la región , en tanto que la contribución de las exportaciones netas al crecimiento ha sido negativa desde 2010 hasta 2013 .
también se reconoce cada vez más que los recortes a la inversión pública , que tradicionalmente han constituido un atajo para la consolidación fiscal en la región , conllevan costos económicos significativos en el largo plazo .
5 de febrero
para los pueblos de los estados miembros de la comunidad de estados independientes el 9 de mayo de 1945 es un día sagrado , una de las fechas más significativas y veneradas .
tenemos una deuda impagable con los que ofrendaron su vida y nos postramos ante la tumba de los caídos en combate , los martirizados en los campos de concentración y las cámaras de tortura nazis , los que sucumbieron víctimas del hambre y la miseria .
cuestiones relativas a la información
reuniones periódicas por teleconferencia para coordinar la planificación conjunta de los eventos principales ;
c. organizaciones del sistema de las naciones unidas 33 - 76 19
la conferencia tendrá lugar bajo los auspicios de la secretaría general del consejo de cooperación del golfo conforme a la solicitud hecha por el presidente hadi a sus homólogos del consejo de cooperación del golfo el 5 de marzo de 2015 .
el reino de marruecos considera totalmente inaceptable la reciente maniobra de la unión africana , por la que solicitó una interacción entre su &quot; enviado especial , &quot; el sr. joaquim chissano , y el consejo de seguridad .
por su parte , el reino de marruecos desea reiterar una vez más su compromiso con el proceso de negociaciones políticas bajo la égida de las naciones unidas .
c. talleres de capacitación o visitas para periodistas a lugares donde se ejecutan proyectos de la organización , en cooperación con los asociados locales del sistema de las naciones unidas , para que los periodistas locales comprendan mejor las cuestiones de las que se ocupan las naciones unidas , y organización de sesiones de capacitación para bibliotecarios locales de las naciones unidas ( 4 ) .
también está decidido a poner freno a los peligros y los horrores del terrorismo , con miras a defender a los ciudadanos de siria y su honor , y a fin de responder al ataque contra las capacidades del país y su pueblo .
que se celebrará el miércoles 18 de marzo de 2015 , a las 10.33 horas
el fortalecimiento del dólar de los estados unidos , sin embargo , podría ser la antesala de un cierto aumento de los desequilibrios mundiales en el período que abarcan las previsiones , aunque no a los niveles observados entre 2006 y 2008 .
con la desaceleración del crecimiento del pib , también se ha ralentizado el ritmo de expansión del empleo , mientras que la brecha entre los géneros en muchos casos sigue ampliándose .
en su resolución de 2014 relativa al fortalecimiento de la eficacia y aumento de la eficiencia de las salvaguardias del organismo , la conferencia general acogió favorablemente , con apoyo del brasil , las aclaraciones e informaciones adicionales presentadas por la secretaría en ese documento complementario .
el brasil respalda por lo tanto plenamente las iniciativas multilaterales encaminadas a preservar y reforzar el cumplimiento de las obligaciones de no proliferación previstas en el tnp , en particular a través del oiea .
se sugiere que las instituciones a todos los niveles deberán tomar medidas de adaptación para poner en práctica la nueva agenda para el desarrollo , lo que exigirá un cambio fundamental en las mentalidades y actitudes junto con un firme liderazgo y visión .
este cambio implicará entablar un diálogo sobre políticas que abarque diferentes intereses sectoriales o políticos , con aportaciones de una amplia variedad de grupos .
tengo el honor de adjuntar a la presente una carta del ministro de relaciones exteriores de la república islámica del irán , excmo. sr. m. javad zarif , con respecto a la situación extremadamente alarmante en el yemen .
también han atacado de manera indiscriminada zonas residenciales , incluidos los campamentos de refugiados , causando muertes y lesiones a civiles inocentes , en particular mujeres y niños .
la oficina de tecnología de la información y las comunicaciones se centrará en el establecimiento de una arquitectura institucional , dirigirá el fortalecimiento de la incorporación de umoja , la seguridad de la información y la resiliencia operacional y se asegurará de que los programas de tecnologías de tic se ajusten a la labor central de las naciones unidas .
a fin de apoyar las propuestas del secretario general sobre la forma en que los objetivos de la organización , los logros previstos y los indicadores de progreso , enunciados en el plan por programas bienal , podrían mejorarse para indicar con mayor claridad las repercusiones de las actividades realizadas , se llevó a cabo un examen de esos elementos aprobados para los bienios 2006-2007 y 2016-2017 .
relatora : sra. kara-kys arakchaa
7 . observa los esfuerzos realizados por el secretario general para establecer el módulo de la cadena de suministro de umoja , y observa también la mejora de la gobernanza de las funciones de adquisición a fin de incluir las operaciones de adquisición en las misiones de mantenimiento de la paz , las misiones políticas especiales , las oficinas situadas fuera de la sede y los tribunales , estableciendo al mismo tiempo un marco de responsabilidad y rendición de cuentas claro , y solicita al secretario general que aumente la visibilidad de la información sobre los proveedores a los que se adjudican contratos y órdenes de compra ;
18a.128 durante el bienio 2016-2017 , los recursos extrapresupuestarios previstos , que ascienden a 437.100 dólares , sufragarían un puesto de contratación local y contribuirían a fomentar la capacidad de las oficinas nacionales de estadística de áfrica central para utilizar tecnologías modernas de recopilación y procesamiento de datos estadísticos comparables y armonizados .
el costo humano de la transferencia ilícita , la acumulación desestabilizadora y el uso indebido de armas pequeñas y armas ligeras
a juicio del secretario general , las mencionadas credenciales provisionales están en regla .
los principios importantes de una buena gobernanza son , entre otros : colaboración o participación de los interesados , equidad , rendición de cuentas , transparencia , eficiencia y eficacia ( véase bodegom y otros , 2012 , an approach for integrating forest governance into national forest-related monitoring systems , fao forestry policy and institutions working paper no . 29 , roma ) .
esta difícil situación apunta a la necesidad de reanudar las negociaciones con las instituciones financieras internacionales , principalmente el fmi , en relación con un nuevo mecanismo financiero , o la identificación de las fuentes alternativas de financiación , que suelen ser difíciles de obtener o mucho menos favorables .
según se especificaba en la orden , esta debía aplicarse especialmente a las decisiones relativas a los nuevos nombramientos y la contratación .
el foro permanente acoge con agrado la participación de expertos indígenas y de las naciones unidas en la mesa redonda sobre el proyecto de índice de desarrollo de los pueblos indígenas .
el foro permanente recomienda que la división de estadística colabore activamente con los pueblos indígenas de los países desarrollados y , en especial , de los países en desarrollo , en particular con las mujeres indígenas , los jóvenes indígenas y las personas indígenas con discapacidad , para elaborar indicadores clave sobre los pueblos indígenas , entre otras cosas para el desglose de datos , que se incluirán en los indicadores generales de la agenda para el desarrollo después de 2015 , cuya aprobación será en marzo de 2016 .
en cumplimiento del artículo 15 del reglamento provisional del consejo de seguridad , el secretario general comunica que ha recibido credenciales firmadas el 8 de mayo de 2015 por el ministro de relaciones exteriores de nueva zelandia en que se indica que el sr. gerardus jacobus van bohemen ha sido nombrado representante de nueva zelandia en el consejo de seguridad .
los pagos recibidos hasta esa misma fecha ascendían a 1.036.201.000 , dólares , con lo que el saldo pendiente era de 40.762.000. dólares .
durante esta primera visita , que coincidió con la inauguración del foro de bangui , celebré conversaciones con representantes de la sociedad civil y la comunidad internacional con base en bangui , así como con las autoridades de transición , a fin de recabar sus opiniones sobre los aspectos prioritarios de la participación de la comisión de consolidación de la paz en la república centroafricana , en un momento crucial del proceso político .
en mi calidad de presidente de la configuración encargada de la república centroafricana de la comisión de consolidación de la paz , visité bangui del 2 al 5 de mayo de 2015 .
a fines de febrero el mlj se escindió y se constituyeron dos nuevos partidos políticos , uno encabezado por el ex presidente del mlj , tijani al-sissi , y el otro por su secretario , bahar idriss abu garda .
al 7 de mayo de 2015 , las cuotas impagadas a la cuenta especial para la unamid ascendían a 263,9 millones de dólares mientras que el total de cuotas pendientes de pago de todas las operaciones de mantenimiento de la paz ascendía a 1.958,6 millones de dólares .
reiterando la necesidad de que la comunidad internacional cumpla todos los compromisos contraídos en relación con el desarrollo económico y social de áfrica ,
en respuesta a sus preguntas , se informó a la comisión consultiva de que el banco que prestaba servicios no cobró cargos bancarios en 2014 a la espera de la conclusión de las negociaciones de un acuerdo , que recientemente se ha alcanzado y que entró en vigor a partir de febrero de 2015 .
3 sectores
myanmar
los mandatos de las misiones , en particular en los ámbitos del desarme , la desmovilización y la reintegración , y la reforma del sector de la seguridad , deberían elaborarse sobre la base de un examen exhaustivo de las necesidades de seguridad a corto , mediano y largo plazo .
la aplicación sostenida de las rigurosas directrices técnicas internacionales sobre municiones es esencial .
el agente de policía que proceda a la incautación de un bien será el administrador de ese bien ( art . 255 de la ley sobre el producto del delito ) .
